name: pypy-nightly
version: '7.3.1'
summary: PyPy is a fast, compliant alternative implementation of the Python language
description: |
  PyPy is a replacement for CPython. It is built using the RPython language
  that was co-developed with it. The main reason to use it instead of CPython
  is speed; it runs generally faster.
license: MIT

grade: stable
confinement: classic

apps:
  pypy:
    command: bin/pypy

base: core
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: ppc64el
  - build-on: s390x

parts:
  pypy:
    plugin: dump
    source:
      - on amd64: http://buildbot.pypy.org/nightly/py3.7/pypy-c-jit-latest-linux64.tar.bz2
      - on arm64: http://buildbot.pypy.org/nightly/py3.7/pypy-c-jit-latest-aarch64.tar.bz2
    override-build: |
      bin/pypy -m compileall -qx '/tests?[_/]' .
      snapcraftctl build
    stage-packages:
      - libfontconfig1
      - libxft2
      - libxrender1
